// ==========================================
// GLOBAL SETTINGS
// ==========================================
Window.SetBackgroundTopColor (0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor (0.0, 0.0, 0.0);

is_password_requested = 0;
animation_started = 0;

// ==========================================
// Loading frames
// ==========================================
total_frame_count = 137;
loop_start_frame = 74;

for (i = 1; i <= total_frame_count; i++) {
    image[i] = Image("intro/frame_" + i + ".png");
}

sprite = Sprite();

// ==========================================
// LUKS SETTINGS
// ==========================================
prompt_sprite = Sprite();
bullet_sprite = Sprite();

prompt_sprite.SetX(Window.GetWidth() / 2 - 150);
prompt_sprite.SetY(Window.GetHeight() - 100);
prompt_sprite.SetZ(100);

bullet_sprite.SetX(Window.GetWidth() / 2 - 150);
bullet_sprite.SetY(Window.GetHeight() - 70);
bullet_sprite.SetZ(100);

fun display_password_callback (prompt, bullets) {
    is_password_requested = 1;

    global.prompt_image = Image.Text(prompt, 1.0, 1.0, 1.0);
    global.bullet_image = Image.Text(bullets, 1.0, 1.0, 1.0);

    prompt_sprite.SetImage(global.prompt_image);
    bullet_sprite.SetImage(global.bullet_image);
}
Plymouth.SetDisplayPasswordFunction(display_password_callback);

fun display_normal_callback () {
    is_password_requested = 0;
    prompt_sprite.SetImage(NULL);
    bullet_sprite.SetImage(NULL);

    animation_started = 1;
}
Plymouth.SetDisplayNormalFunction(display_normal_callback);

// ==========================================
// ANIMATION LOOP
// ==========================================
progress = 1;
tick_counter = 0;

fun refresh_callback () {
    // Animacja "stoi w miejscu", dopóki zmienna animation_started wynosi 0
    if (animation_started == 1) {
        tick_counter++;

        sprite.SetX(Window.GetWidth() / 2 - image[progress].GetWidth() / 2);
        sprite.SetY(Window.GetHeight() / 2 - image[progress].GetHeight() / 2);
        sprite.SetImage(image[progress]);

        if (tick_counter >= 4) {
            progress++;
            tick_counter = 0;

            // Zapętlenie końcówki, gdyby system ładował się dłużej
            if (progress > total_frame_count) {
                progress = loop_start_frame;
            }
        }
    }
}
Plymouth.SetRefreshFunction (refresh_callback);
